[[project]]
name = "Helm chart"
desc = "Creating helm chart from scratch"
tags = ["k8s", "helm"]
links = [
    {name = "github", url = "https://github.com/Pawan-666/helm_from_scratch"},
]

[[project]]
name = "Gitops"
desc = "Gitops using jenkins, eks, argocd"
tags = ["gitops", "k8s", "jenkins", "eks"]
links = [
    {name = "github1", url = "https://github.com/Pawan-666/gitops-1"},
    {name = "github2", url = "https://github.com/Pawan-666/git-ops2"},
]

[[project]]
name = "Terrafrom"
desc = "operating terrafrom at different levels"
tags = ["aws", "terrafrom"]
links = [
    {name = "github", url = "https://github.com/Pawan-666/terraform-aws"},
]

# [[project]]
# name = "100days python"
# desc = "100 days of python bootcamp"
# tags = ["python"]
# links = [
#     {name = "github", url = "https://github.com/Pawan-666/100days-python"},
# ]

[[project]]
name = "Macos dotfiles"
desc = "dotfiles for macos"
tags = ["yazi", "wezterm", "macos", "vim", "lvim", "mpv", "lf", "alacritty", "tmux", "zsh"]
links = [
    {name = "github", url = "https://github.com/Pawan-666/mac_dotfiles"},
]

[[project]]
name = "Linux dotfiles"
desc = "dotfiles for linux desktop"
tags = ["linux", "vim", "bspwm", "i3", "lvim", "tmux", "mpv", "lf", "alacritty"]
links = [
    {name = "github", url = "https://github.com/Pawan-666/linux_dotfiles"},
]

